---
- hosts: django_ubuntu
  vars_files:
    - vars.yml
  gather_facts: false
  become: yes

  tasks:
    - name: Install system packages
      apt: pkg={{ item }} update-cache=yes
      with_items: "{{ system_packages }}"

    - name: Create directory for app
      file: path={{ install_root }}/{{ project_name }} state=directory